version: '3.4'

services:
  cadastronumeros-api:
    image: cadastronumeros-api:latest
    labels:
      kompose.image-pull-policy: "Never"
    build:
      context: .
      dockerfile: CadastroNumeros.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    networks:
      - mynw
      
  cadastronumeros-consumer:
    image: cadastronumeros-consumer:latest
    labels:
      kompose.image-pull-policy: "Never"
    build:
      context: .
      dockerfile: CadastroNumeros.Contato.Consumer/Dockerfile
    environment:
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
    depends_on:
      - rabbitmq
    networks:
      - mynw
      
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - mynw

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    ports:
      - "9100:9100"
    networks:
      - mynw

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - mynw

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - mynw       
      
networks:
  mynw:
    driver: bridge
