apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/rabbitmq"  # Diretório local no Docker Desktop
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""  # Garante que o PVC use o PV manualmente criado
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      securityContext:
        fsGroup: 999  # Garante permissões corretas no volume
      containers:
        - name: rabbitmq
          image: rabbitmq:4.0.6-management-alpine
          env:
            - name: "RABBITMQ_ERLANG_COOKIE"
              value: "xtXjHTZ07szmW3ktd0Wmb7vDZPq8h8OpdLnytiGJ3k5RzshF5hUtMfnvHgVmG66z1u6"
          ports:
            - containerPort: 5672
            - containerPort: 15672
          securityContext:
            runAsUser: 999
            runAsGroup: 999
          volumeMounts:
            - mountPath: /var/lib/rabbitmq/fiap
              name: rabbitmq-storage
      volumes:
        - name: rabbitmq-storage
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
  type: NodePort  # Expor no Docker Desktop
